- name: create vpc 
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import variables
      include_vars: vars/vpc_setup
    - name: create vpc 
      # https://docs.ansible.com/ansible/latest/collections/amazon/aws/ec2_vpc_net_module.html
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
        state: "{{state}}"
      register: vpcout
    - debug:
        var: vpcout
    - name : create public subnet 1
      # https://docs.ansible.com/ansible/latest/collections/amazon/aws/ec2_vpc_subnet_module.html
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone1}}"
        state: "{{state}}"
        cidr: "{{PubSub1Cidr}}"
        map_public: yes
        resource_tags:
          # this is the name that displays in subnet console
          Name: vprofile-pubsub1
      register: pubsub1_out
    - name : create public subnet 2
      # https://docs.ansible.com/ansible/latest/collections/amazon/aws/ec2_vpc_subnet_module.html
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone2}}"
        state: "{{state}}"
        cidr: "{{PubSub2Cidr}}"
        map_public: yes
        resource_tags:
          # this is the name that displays in subnet console
          Name: vprofile-pubsub2
      register: pubsub2_out
    - name : create public subnet 3
      # https://docs.ansible.com/ansible/latest/collections/amazon/aws/ec2_vpc_subnet_module.html
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone3}}"
        state: "{{state}}"
        cidr: "{{PubSub3Cidr}}"
        map_public: yes
        resource_tags:
          # this is the name that displays in subnet console
          Name: vprofile-pubsub3
      register: pubsub3_out
    - name: internet gateway
      # https://docs.ansible.com/ansible/latest/collections/amazon/aws/ec2_vpc_igw_module.html
      ec2_vpc_igw: 
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        state: "{{state}}"
        resource_tags:
          # this is the name that displays in subnet console
          Name: vprofile-igw
      register: igw_out
    - name: route table
      # https://docs.ansible.com/ansible/latest/collections/amazon/aws/ec_vpc_route_table_module.html
      ec_vpc_route_table:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        tags: 
          Name: vprofile-pub-routetable
        subnets:
          - "{{pubsub1_out.subnet.id}}"
          - "{{pubsub2_out.subnet.id}}"
          - "{{pubsub3_out.subnet.id}}"
        routes: 
          - dest: 0.0.0.0/0 
          - gateway_id: "{{igw_out.gateway_id}}"
        register: pub_routetable_out


